[package]
name = "view"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kajiya = { path = "../../lib/kajiya" }
kajiya-simple = { path = "../../lib/kajiya-simple", features = [
    "dear-imgui",
    "winit_serde",
] }
kajiya-asset-pipe = { path = "../../lib/kajiya-asset-pipe" }

anyhow = "1.0"
dolly = { path = "/home/max/dev/dolly" }
imgui = "0.12"
log = "0.4"
ron = "0.10.1"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
toml = "0.8.23"
splines = { version = "5.0.0", features = ["glam"] }

[features]
dlss = ["kajiya/dlss"]
puffin-server = ['kajiya-simple/puffin-server']
